//    ________.____    .______________________   ___ ___     ________.______________ ____   ____  ____. ____   ________
//   /  _____/|    |   |   \__    ___|_   ___ \ /   |   \   /  _____/|   \_   _____/ \   \ /   / |    | \   \ /   /_   |
//  /   \  ___|    |   |   | |    |  /    \  \//    ~    \ /   \  ___|   ||    __)    \   Y   /  |    |  \   Y   / |   |
//  \    \_\  \    |___|   | |    |  \     \___\    Y    / \    \_\  \   ||     \      \     /\__|    |   \     /  |   |
//   \______  /_______ \___| |____|   \______  /\___|_  /   \______  /___|\___  /       \___/\________|    \___/   |___| .3

var code = '<div id="fxctrlout">\n';
code += '<h1 class="fxhead">Output fx</h1>\n';
code += '<ul id="outlist">\n';
code += '<li data-fnc="zoom">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">zoom: <span id="zoominfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="zoomseed" min="0" max="10" step="0.01" value="0">\n';
code += '</div>\n';
code += '</li>\n';

code += '<li data-fnc="latglitch">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">latglitch: <span id="outseedinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="outlatseed" min="0" max="1000" step="1" value="0">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="dither">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Dither: <span id="outdithinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="outdith" min="0" max="9" step="1" value="0">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="invert">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Invert: <span id="outinvinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="outinv" min="0" max="1" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="mirror">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Mirror / scale: <span id="mirrorinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="mirror" min="0" max="10" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="flip">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Flip: <span id="flipinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="flip" min="0" max="3" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="noise">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Noize: <span id="filterzinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="filterz" min="0" max="9" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="slicer">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Slicer: <span id="slicerzinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="slicerz" min="0" max="5" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="monochroma">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Mono Chroma: <span id="monochromainfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="monochroma" min="0" max="3" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="rgbdesync">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">RGB desync: <span id="rgb1info">0</span></h2>\n';
code += '<input class="potard" type="range" id="rgb1" min="0" max="1" step="1">\n';
code += '<input class="potard" type="range" id="rgbR" min="0" max="2000" step="1">\n';
code += '<input class="potard" type="range" id="rgbG" min="0" max="2000" step="1">\n';
code += '<input class="potard" type="range" id="rgbB" min="0" max="2000" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="filtering">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">filters: <span id="filteringinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="filtering" min="0" max="30" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="pixelate">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">pixelate: <span id="pixelateinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="pixelateon" min="0" max="200" step="1">\n';
code += '<input class="potard" type="range" id="pixelatemode" min="0" max="1" step="1">\n';
code += '<input class="potard" type="range" id="pixelateforce" min="0" max="14" step="1">\n';

code += '</div>\n';
code += '</li>\n';
code += '</ul>\n';
code += '</div>\n';
code += '<div id="fxctrllr1">\n';
code += '<h1 class="fxhead">Layer 1 fx</h1>\n';
code += '<ul id="lr1list">\n';
code += '<li data-fnc="zoom">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">zoom: <span id="lr1zoominfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr1zoomseed" min="0" max="10" step="0.01" value="0">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="latglitch">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">latglitch: <span id="lr1seedinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr1latseed" min="0" max="1000" step="1" value="0">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="dither">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Dither: <span id="lr1dithinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr1dith" min="0" max="9" step="1" value="0">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="invert">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Invert: <span id="lr1invinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr1inv" min="0" max="1" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="mirror">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Mirror / scale: <span id="lr1mirrorinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr1mirror" min="0" max="10" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="flip">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Flip: <span id="lr1flipinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr1flip" min="0" max="3" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="noise">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Noize: <span id="lr1filterzinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr1filterz" min="0" max="9" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="slicer">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Slicer: <span id="lr1slicerzinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr1slicerz" min="0" max="5" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="monochroma">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Mono Chroma: <span id="lr1monochromainfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr1monochroma" min="0" max="3" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="rgbdesync">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">RGB desync: <span id="rgb1lr1info">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr1rgb1" min="0" max="1" step="1">\n';
code += '<input class="potard" type="range" id="lr1rgbR" min="0" max="2000" step="1">\n';
code += '<input class="potard" type="range" id="lr1rgbG" min="0" max="2000" step="1">\n';
code += '<input class="potard" type="range" id="lr1rgbB" min="0" max="2000" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="filtering">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">filters: <span id="lr1filteringinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr1filtering" min="0" max="30" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="pixelate">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">pixelate: <span id="lr1pixelateinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr1pixelateon" min="0" max="200" step="1">\n';
code += '<input class="potard" type="range" id="lr1pixelatemode" min="0" max="1" step="1">\n';
code += '<input class="potard" type="range" id="lr1pixelateforce" min="0" max="14" step="1">\n';

code += '</div>\n';
code += '</li>\n';
code += '</ul>\n';
code += '</div>\n';
code += '<div id="fxctrllr2">\n';
code += '<h1 class="fxhead">Layer 2 fx</h1>\n';
code += '<ul id="lr2list">\n';
code += '<li data-fnc="zoom">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">zoom: <span id="lr2zoominfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr2zoomseed" min="0" max="10" step="0.01" value="0">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="latglitch">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">latglitch: <span id="lr2seedinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr2latseed" min="0" max="1000" step="1" value="0">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="dither">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Dither: <span id="lr2dithinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr2dith" min="0" max="9" step="1" value="0">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="invert">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Invert: <span id="lr2invinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr2inv" min="0" max="1" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="mirror">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Mirror / scale:<span id="lr2mirrorinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr2mirror" min="0" max="10" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="flip">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Flip: <span id="lr2flipinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr2flip" min="0" max="3" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="noise">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Noize: <span id="lr2filterzinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr2filterz" min="0" max="9" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="slicer">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Slicer: <span id="lr2slicerzinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr2slicerz" min="0" max="5" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="monochroma">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">Mono Chroma: <span id="lr2monochromainfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr2monochroma" min="0" max="3" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="rgbdesync">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">RGB desync: <span id="rgb1lr2info">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr2rgb1" min="0" max="1" step="1">\n';
code += '<input class="potard" type="range" id="lr2rgbR" min="0" max="2000" step="1">\n';
code += '<input class="potard" type="range" id="lr2rgbG" min="0" max="2000" step="1">\n';
code += '<input class="potard" type="range" id="lr2rgbB" min="0" max="2000" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="filtering">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">filters: <span id="lr2filteringinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr2filtering" min="0" max="30" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '<li data-fnc="pixelate">\n';
code += '<div class="ctrlblock">\n';
code += '<h2 class="item">pixelate: <span id="lr2pixelateinfo">0</span></h2>\n';
code += '<input class="potard" type="range" id="lr2pixelateon" min="0" max="200" step="1">\n';
code += '<input class="potard" type="range" id="lr2pixelatemode" min="0" max="1" step="1">\n';
code += '<input class="potard" type="range" id="lr2pixelateforce" min="0" max="14" step="1">\n';
code += '</div>\n';
code += '</li>\n';
code += '</ul>\n';
code += '</div>\n';
code += '<div id="layermixer">\n';
code += '<div>\n';
code += '<canvas id="canvas_layer_2"></canvas>\n';
code += '</div>\n';
code += '<br>\n';
code += '<div>\n';
code += '<div class="ctrlblock" id="opablock">\n';
code += '<h2 class="item2">Opacity: <span id="opainfo"></span></h2>\n';
code += '<input class="inpt potard" class="potard" type="range" value="1" min="0" max="1" step="0.01" id="l2opacity">\n';
code += '</div>\n';
code += '<div class="ctrlblock" id="compoblock">\n';
code += '<h2 class="item2">Mode: <span id="compinfo"></span></h2>\n';
code += '<input class="inpt potard" class="potard" type="range" value="1" min="0" max="28" step="1" id="l2compmode">\n';
code += '</div>\n';
code += '</div>\n';
code += '<br>\n';
code += '<div>\n';
code += '<canvas id="canvas_layer_1"></canvas>\n';
code += '</div>\n';
code += '</div>\n';
code += '<div id="outmonitor" style="">\n';
code += '<canvas class="fr" id="preview_canvas" style="height:240px"></canvas>\n';
code += '<br>\n';
code += '<div id="monitor_controls">\n';
code += '<button id="outpopup"></button> <div id="rez"><span id="resolution"></span>\n';
code += '<select id="rezolution">\n';
code += '<option value="qvga">QVGA</option>\n';
code += '<option value="vga">VGA</option>\n';
code += '<option value="svga">SVGA</option>\n';
code += '<option value="xga">XGA</option>\n';
code += '</select><small id="status"></small></div><button id="panic">Panic!</button><button id="rdmfx">FX_rdm</button><select id="randomfxforce" style="position:relative;top:-5px;"><option value="1">1</option><option value="9">1</option><option value="8">2</option><option value="7">3</option><option value="6">4</option><option value="5">5</option><option value="4">6</option><option value="3">7</option><option value="2">8</option></select>\n';
code += '<br><button id="startaudio"></button><button id="record" style="top:2px;">REC</button><button id="recstop" style="top:2px;">STOP</button><select id="recformat" style="position:relative;top:2px;"><option value="0">WebM</option><option value="1">GIF</option></select>\n';
//code += '<button id="gifrec"></button><br>\n';
code += '\n';

code += '<br><br><button id="savekit"></button>\n';
code += '<div class="loadkit">\n';
code += '<input type="file" id="loadkit" name="loadkit">\n';
code += '</div>\n';
code += '<button id="ennablemidi"></button>\n';
code += '<button id="midilearn"></button>\n';
code += '<button id="savemidisetup"></button>\n';
code += '<button id="loadmidisetup"></button>\n';
code += '<button id="openvideopong">SEARCH VIDEOPONG.NET</button><button id="remotegif">LOAD A REMOTE GIF</button>\n';
code += '</div> </div>\n';
code += '<div id="messagebox"><p>WELCOME TO GLITCH GIF VJ 1.3.1</p></div>\n';
//code += '<div id="outputrecgif"></div>\n';
code += '<ul id="bankselector" class="banks">&nbsp;&nbsp;   BANK <li data-bank="bank-1" class="selected">1</li><li data-bank="bank-2">2</li><li data-bank="bank-3">3</li></ul>\n';
code += '<div class="bank selected-bank" id="bank-1">\n';
code += '<div class="source_block" id="source_A">\n';
code += '<h1 class="head"><span id="bk_A" class="assign-note" data-note="">A';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select>\n';
code += '<form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="A" type="file" class="img_input" name="loadimage_A" id="inputimage_A" class="imloader">\n';
code += '</div>\n';
code += '</form></h1>\n';
code += '<div class="imsources" id="imsource_A"></div>\n';
code += '<div><select  class="src_ctrl_select" id="src_ctrl_A"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedA" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_A" min="-100" max="100" value="1"step="1"> </div>\n';
code += '</div>\n';

code += '<div class="source_block" id="source_Z">\n';
code += '<h1 class="head"><span id="bk_Z" class="assign-note" data-note="">Z';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select><form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="Z" type="file" class="img_input" name="loadimage_Z" id="inputimage_Z" class="imloader">\n';
code += '</div>\n';
code += '</form></h1>\n';
code += '<div class="imsources" id="imsource_Z"></div>\n';
code += '<div><select class="src_ctrl_select" id="src_ctrl_Z"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedZ" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_Z" min="-100" max="100" value="1"step="1"> </div>\n';

code += '</div>\n';
code += '<div class="source_block" id="source_E">\n';
code += '<h1 class="head"><span id="bk_E" class="assign-note" data-note="">E';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select>\n';
code += '<form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="E" type="file" class="img_input" name="loadimage_E" id="inputimage_E" class="imloader">\n';
code += '</div>\n';
code += '</form></h1>\n';
code += '<div class="imsources" id="imsource_E"></div>\n';
code += '<div><select class="src_ctrl_select" id="src_ctrl_E"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedE" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_E" min="-100" max="100" value="1"step="1"> </div>\n';

code += '</div>\n';
code += '<div class="source_block" id="source_R">\n';
code += '<h1 class="head"><span id="bk_R" class="assign-note" data-note="">R';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select>\n';
code += '<form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="R" type="file" class="img_input" name="loadimage_R" id="inputimage_R" class="imloader">\n';
code += '</div>\n';
code += '</form></h1>\n';
code += '<div class="imsources" id="imsource_R"></div>\n';
code += '<div><select class="src_ctrl_select" id="src_ctrl_R"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedR" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_R" min="-100" max="100" value="1"step="1"> </div>\n';

code += '</div>\n';
code += '<div class="source_block" id="source_T">\n';
code += '<h1 class="head"><span id="bk_T" class="assign-note" data-note="">T';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select>\n';
code += '<form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="T" type="file" class="img_input" name="loadimage_T" id="inputimage_T" class="imloader">\n';
code += '</div>\n';
code += '</form>\n';
code += '</h1>\n';
code += '<div class="imsources" id="imsource_T"></div>\n';
code += '<div><select class="src_ctrl_select" id="src_ctrl_T"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedT" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_T" min="-100" max="100" value="1"step="1"> </div>\n';

code += '</div>\n';
code += '<div class="source_block" id="source_Y">\n';
code += '<h1 class="head"><span id="bk_Y" class="assign-note" data-note="">Y';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select>\n';
code += '<form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="Y" type="file" class="img_input" name="loadimage_Y" id="inputimage_Y" class="imloader">\n';
code += '</div>\n';
code += '</form></h1>\n';
code += '<div class="imsources" id="imsource_Y"></div>\n';
code += '<div><select class="src_ctrl_select" class="src_ctrl_select" id="src_ctrl_Y"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedY" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_Y" min="-100" max="100" value="1"step="1"> </div>\n';

code += '</div>\n';
code += '</div>\n';



code += '<div class="bank hidden" id="bank-2">\n';
code += '<div class="source_block" id="source_Q">\n';
code += '<h1 class="head"><span id="bk_Q" class="assign-note" data-note="">Q';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select>\n';
code += '<form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="Q" type="file" class="img_input" name="loadimage_A" id="inputimage_Q" class="imloader">\n';
code += '</div>\n';
code += '</form></h1>\n';
code += '<div class="imsources" id="imsource_Q"></div>\n';
code += '<div><select class="src_ctrl_select" id="src_ctrl_Q"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedQ" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_Q" min="-100" max="100" value="1"step="1"> </div>\n';

code += '</div>\n';
code += '<div class="source_block" id="source_S">\n';
code += '<h1 class="head"><span id="bk_S" class="assign-note" data-note="">S';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select><form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="S" type="file" class="img_input" name="loadimage_S" id="inputimage_S" class="imloader">\n';
code += '</div>\n';
code += '</form></h1>\n';
code += '<div class="imsources" id="imsource_S"></div>\n';
code += '<div><select class="src_ctrl_select" id="src_ctrl_S"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedS" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_S" min="-100" max="100" value="1"step="1"> </div>\n';

code += '</div>\n';
code += '<div class="source_block" id="source_D">\n';
code += '<h1 class="head"><span id="bk_D" class="assign-note" data-note="">D';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select>\n';
code += '<form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="D" type="file" class="img_input" name="loadimage_D" id="inputimage_D" class="imloader">\n';
code += '</div>\n';
code += '</form></h1>\n';
code += '<div class="imsources" id="imsource_D"></div>\n';
code += '<div><select class="src_ctrl_select" id="src_ctrl_D"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedD" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_D" min="-100" max="100" value="1"step="1"> </div>\n';

code += '</div>\n';
code += '<div class="source_block" id="source_F">\n';
code += '<h1 class="head"><span id="bk_F" class="assign-note" data-note="">F';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select>\n';
code += '<form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="F" type="file" class="img_input" name="loadimage_F" id="inputimage_F" class="imloader">\n';
code += '</div>\n';
code += '</form></h1>\n';
code += '<div class="imsources" id="imsource_F"></div>\n';
code += '<div><select class="src_ctrl_select" id="src_ctrl_F"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedF" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_F" min="-100" max="100" value="1"step="1"> </div>\n';

code += '</div>\n';
code += '<div class="source_block" id="source_G">\n';
code += '<h1 class="head"><span id="bk_G" class="assign-note" data-note="">G';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select>\n';
code += '<form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="G" type="file" class="img_input" name="loadimage_G" id="inputimage_G" class="imloader">\n';
code += '</div>\n';
code += '</form>\n';
code += '</h1>\n';
code += '<div class="imsources" id="imsource_G"></div>\n';
code += '<div><select class="src_ctrl_select" id="src_ctrl_G"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedG" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_G" min="-100" max="100" value="1"step="1"> </div>\n';

code += '</div>\n';
code += '<div class="source_block" id="source_H">\n';
code += '<h1 class="head"><span id="bk_H" class="assign-note" data-note="">H';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select>\n';
code += '<form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="H" type="file" class="img_input" name="loadimage_H" id="inputimage_H" class="imloader">\n';
code += '</div>\n';
code += '</form></h1>\n';
code += '<div class="imsources" id="imsource_H"></div>\n';
code += '<div><select class="src_ctrl_select" id="src_ctrl_H"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedH" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_H" min="-100" max="100" value="1"step="1"> </div>\n';

code += '</div>\n';
code += '</div>\n';

code += '<div class="bank hidden" id="bank-3">\n';
code += '<div class="source_block" id="source_W">\n';
code += '<h1 class="head"><span id="bk_W" class="assign-note" data-note="">W';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select>\n';
code += '<form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="W" type="file" class="img_input" name="loadimage_W" id="inputimage_W" class="imloader">\n';
code += '</div>\n';
code += '</form></h1>\n';
code += '<div class="imsources" id="imsource_W"></div>\n';
code += '<div><select class="src_ctrl_select" id="src_ctrl_W"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedW" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_W" min="-100" max="100" value="1"step="1"> </div>\n';

code += '</div>\n';
code += '<div class="source_block" id="source_X">\n';
code += '<h1 class="head"><span id="bk_X" class="assign-note" data-note="">X';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select><form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="X" type="file" class="img_input" name="loadimage_X" id="inputimage_X" class="imloader">\n';
code += '</div>\n';
code += '</form></h1>\n';
code += '<div class="imsources" id="imsource_X"></div>\n';
code += '<div><select class="src_ctrl_select" id="src_ctrl_X"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedX" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_X" min="-100" max="100" value="1"step="1"></div>\n';

code += '</div>\n';
code += '<div class="source_block" id="source_C">\n';
code += '<h1 class="head"><span id="bk_C" class="assign-note" data-note="">C';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select>\n';
code += '<form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="C" type="file" class="img_input" name="loadimage_C" id="inputimage_C" class="imloader">\n';
code += '</div>\n';
code += '</form></h1>\n';
code += '<div class="imsources" id="imsource_C"></div>\n';
code += '<div><select class="src_ctrl_select" id="src_ctrl_C"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedC" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_C" min="-100" max="100" value="1"step="1"> </div>\n';

code += '</div>\n';
code += '<div class="source_block" id="source_V">\n';
code += '<h1 class="head"><span id="bk_V" class="assign-note" data-note="">V';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select>\n';
code += '<form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="V" type="file" class="img_input" name="loadimage_V" id="inputimage_V" class="imloader">\n';
code += '</div>\n';
code += '</form></h1>\n';
code += '<div class="imsources" id="imsource_V"></div>\n';
code += '<div><select class="src_ctrl_select" id="src_ctrl_V"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedV" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_V" min="-100" max="100" value="1"step="1"> </div>\n';

code += '</div>\n';
code += '<div class="source_block" id="source_B">\n';
code += '<h1 class="head"><span id="bk_B" class="assign-note" data-note="">B';
code += '</span><select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select>\n';
code += '<form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="B" type="file" class="img_input" name="loadimage_B" id="inputimage_B" class="imloader">\n';
code += '</div>\n';
code += '</form>\n';
code += '</h1>\n';
code += '<div class="imsources" id="imsource_B"></div>\n';
code += '<div><select class="src_ctrl_select" id="src_ctrl_B"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedB" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_B" min="-100" max="100" value="1"step="1"> </div>\n';

code += '</div>\n';
code += '<div class="source_block" id="source_N">\n';
code += '<h1 class="head"><span id="bk_N" class="assign-note" data-note="">N';
code += '<select>\n';
code += '<option value="L1">layer 1</option>\n';
code += '<option value="L2">layer 2</option>\n';
code += '</select>\n';
code += '<form>\n';
code += '<div class="upload">\n';
code += '<input data-layer="N" type="file" class="img_input" name="loadimage_N" id="inputimage_N" class="imloader">\n';
code += '</div>\n';
code += '</form></h1>\n';
code += '<div class="imsources" id="imsource_N"></div>\n';
code += '<div><select class="src_ctrl_select" class="src_ctrl_select" id="src_ctrl_N"><option>normal</option><option>control_speed</option><option>random</option></select>\n';
code += '<input class="speed_sldr potard" type="range"  id="speedN" min="0" max="300" value="1"step="1" ><input class="speed_sldr potard double" type="range"  id="ctrl_speed_N" min="-100" max="100" value="1"step="1"> </div>\n';

code += '</div>\n';
code += '</div>\n';
code +='<div id="generators">Generator<br> & more fx</div>'
code += '<div id="blockopacity">Opacity:<br><input class="potard" type="range" id="speopacity" min="0" max="1" step="0.01"></div><div id="blockcompmode">Compositing mode:<br><input class="potard" type="range" id="specompmode" min="0" max="28"></div><div id="specialsources">';
code +='<div class="spe_tab" id="spetab_1">';
//code +=

code +='<canvas style="width:200px;height:150px;display:inline-block;border:1px solid lime;" id="txtcanvas"></canvas>';
code +='<div class="ctrl_spe">speed:<input class="potard" type="range" id="txtspeedloop" min="10" max="600" step="5">fontsize:<input class="potard" type="range" id="fontsize"  min="5" max="500" step="1" >font-family:<input class="potard" type="range" id="fontfamily" min="1" max="13" step="1">mode:<input class="potard" type="range" id="txty" min="0" max="7" step="1">txt src:<input class="potard" type="range" id="txt-mode" min="0" max="10" step="1" ><input class="potard" type="range" min="0" max="200" value="0" id="txtmovespeed" ><br>';

//code +=
//code +=
//code +=
code +='<input type="text" class="txtinput" id="txtsource" value="GLITCH GIF VJ /// A 100% HTML5 JAVASCRIPT VJ SOFTWARE THAT WORKS IN YOUR BROWSER /// AZOPCORP. 2016 /// HTTPS://AZOPCORP.COM"><input type="text" id="fontcolor" value="#000000"><button id="txtgo">Go</button><button id="stoptxtclear">stop</button></div></div>';
code +='<div class="spe_tab" id="spetab_2"><canvas id="vgacanvas" style="width:200px;height:150px;display:inline-block;border:1px solid lime;"></canvas><div class="ctrl_spe"><input class="potard" id="vgabitmap"  class="potard" type="range" min="0" max="4095"><input class="potard" id="vgascale"  class="potard" type="range" min="1" max="80"><input class="potard" id="vgaR"  class="potard" type="range" min="0" max="255"><input class="potard" id="vgaG"  class="potard" type="range" min="0" max="255"><input class="potard" id="vgaB"  class="potard" type="range" min="0" max="255"><input class="potard" id="vgaA"  class="potard" type="range" min="0" max="255"><br><br><button id="vgardm">random</button><br><button id="vgago">Go</button></div></div>';
code +='<div class="spe_tab" id="spetab_3"><canvas id="b64canvas" style="width:200px;height:150px;display:inline-block;border:1px solid lime;"></canvas><div class="ctrl_spe"><input class="potard" type="range" id="glitch64force" min="0" max="4" step="1"><br><br><select id="glitchsrc"><option value="layer1">layer1</option><option value="layer2">layer2</option></select><br><br><button id="glitchgo">Go</button></div></div>\n';
//code +=audio
//code +=
//code +=
code +='<div class="spe_tab" id="spetab_4"><canvas id="videocanvas" style="width:200px;height:150px;display:inline-block;border:1px solid lime;"></canvas><div class="ctrl_spe"><br><br><button id="startvideoinput">Go</button></div></div>\n';
code +='<div class="spe_tab" id="spetab_5"><canvas id="osccanvas" style="width:200px;height:150px;display:inline-block;border:1px solid lime;"></canvas><div class="ctrl_spe"><input type="text" id="osccolor1" value="#000000"><input type="text" id="osccolor2" value="#ffffff"><br><br><br><br><button id="oscstart">Go</button></div></div>\n';

code += '<div id="menuspesources">\n';
code += '<ul id="spe_menu"><li id="spe_1" data-order="txt"></li><li id="spe_2" data-order="vga"></li><li id="spe_3" data-order="b64"></li><li id="spe_4" data-order="video"></li><li id="spe_5" data-order="osc"></li>\n';

code += '</ul>';
code += '</div>';
code += '</div>';
code +='	<div id="seqbox">  <div id="seqcontrols">    <button id="start">Start</button><button id="stop">Stop</button>   <input type="text" id="bpm" class="num"value="140"><select id="beatrez" style="position:relative;top:-5px;"><option value="1">--</option><option value="4">4</option><option value="8">8</option><option value="16">16</option></select><button id="tap">TAP</button> <button id="randomise">Randomise</button> </div>  <div id="seqsteps">    <div class="step"><select id="step1"><option>--</option><option>A</option><option>Z</option><option>E</option><option>R</option><option>T</option><option>Y</option><option>Q</option><option>S</option><option>D</option><option>F</option><option>G</option><option>H</option>      <option>W</option><option>X</option><option>C</option><option>V</option><option>B</option><option>N</option></select></div>    <div class="step"><select id="step2"><option>--</option><option>A</option><option>Z</option><option>E</option><option>R</option><option>T</option><option>Y</option><option>Q</option><option>S</option><option>D</option><option>F</option><option>G</option><option>H</option>      <option>W</option><option>X</option><option>C</option><option>V</option><option>B</option><option>N</option></select></div>    <div class="step"><select id="step3"><option>--</option><option>A</option><option>Z</option><option>E</option><option>R</option><option>T</option><option>Y</option><option>Q</option><option>S</option><option>D</option><option>F</option><option>G</option><option>H</option>      <option>W</option><option>X</option><option>C</option><option>V</option><option>B</option><option>N</option></select></div>    <div class="step"><select id="step4"><option>--</option><option>A</option><option>Z</option><option>E</option><option>R</option><option>T</option><option>Y</option><option>Q</option><option>S</option><option>D</option><option>F</option><option>G</option><option>H</option>      <option>W</option><option>X</option><option>C</option><option>V</option><option>B</option><option>N</option></select></div>    <div class="step"><select id="step5"><option>--</option><option>A</option><option>Z</option><option>E</option><option>R</option><option>T</option><option>Y</option><option>Q</option><option>S</option><option>D</option><option>F</option><option>G</option><option>H</option>      <option>W</option><option>X</option><option>C</option><option>V</option><option>B</option><option>N</option></select></div>    <div class="step"><select id="step6"><option>--</option><option>A</option><option>Z</option><option>E</option><option>R</option><option>T</option><option>Y</option><option>Q</option><option>S</option><option>D</option><option>F</option><option>G</option><option>H</option>      <option>W</option><option>X</option><option>C</option><option>V</option><option>B</option><option>N</option></select></div>    <div class="step"><select id="step7"><option>--</option><option>A</option><option>Z</option><option>E</option><option>R</option><option>T</option><option>Y</option><option>Q</option><option>S</option><option>D</option><option>F</option><option>G</option><option>H</option>      <option>W</option><option>X</option><option>C</option><option>V</option><option>B</option><option>N</option></select></div>    <div class="step"><select id="step8"><option>--</option><option>A</option><option>Z</option><option>E</option><option>R</option><option>T</option><option>Y</option><option>Q</option><option>S</option><option>D</option><option>F</option><option>G</option><option>H</option>      <option>W</option><option>X</option><option>C</option><option>V</option><option>B</option><option>N</option></select></div>           <div class="step"><select id="step9"><option>--</option><option>A</option><option>Z</option><option>E</option><option>R</option><option>T</option><option>Y</option><option>Q</option><option>S</option><option>D</option><option>F</option><option>G</option><option>H</option>      <option>W</option><option>X</option><option>C</option><option>V</option><option>B</option><option>N</option></select></div>    <div class="step"><select id="step10"><option>--</option><option>A</option><option>Z</option><option>E</option><option>R</option><option>T</option><option>Y</option><option>Q</option><option>S</option><option>D</option><option>F</option><option>G</option><option>H</option>      <option>W</option><option>X</option><option>C</option><option>V</option><option>B</option><option>N</option></select></div>    <div class="step"><select id="step11"><option>--</option><option>A</option><option>Z</option><option>E</option><option>R</option><option>T</option><option>Y</option><option>Q</option><option>S</option><option>D</option><option>F</option><option>G</option><option>H</option>      <option>W</option><option>X</option><option>C</option><option>V</option><option>B</option><option>N</option></select></div>    <div class="step"><select id="step12"><option>--</option><option>A</option><option>Z</option><option>E</option><option>R</option><option>T</option><option>Y</option><option>Q</option><option>S</option><option>D</option><option>F</option><option>G</option><option>H</option>      <option>W</option><option>X</option><option>C</option><option>V</option><option>B</option><option>N</option></select></div>    <div class="step"><select id="step13"><option>--</option><option>A</option><option>Z</option><option>E</option><option>R</option><option>T</option><option>Y</option><option>Q</option><option>S</option><option>D</option><option>F</option><option>G</option><option>H</option>      <option>W</option><option>X</option><option>C</option><option>V</option><option>B</option><option>N</option></select></div>    <div class="step"><select id="step14"><option>--</option><option>A</option><option>Z</option><option>E</option><option>R</option><option>T</option><option>Y</option><option>Q</option><option>S</option><option>D</option><option>F</option><option>G</option><option>H</option>      <option>W</option><option>X</option><option>C</option><option>V</option><option>B</option><option>N</option></select></div>    <div class="step"><select id="step15"><option>--</option><option>A</option><option>Z</option><option>E</option><option>R</option><option>T</option><option>Y</option><option>Q</option><option>S</option><option>D</option><option>F</option><option>G</option><option>H</option>      <option>W</option><option>X</option><option>C</option><option>V</option><option>B</option><option>N</option></select></div>    <div class="step"><select id="step16"><option>--</option><option>A</option><option>Z</option><option>E</option><option>R</option><option>T</option><option>Y</option><option>Q</option><option>S</option><option>D</option><option>F</option><option>G</option><option>H</option>      <option>W</option><option>X</option><option>C</option><option>V</option><option>B</option><option>N</option></select></div>  </div></div>';

code += '<div id="logo"><pre>';
code += '    ________.____    .______________________   ___ ___     ________.______________ ____   ____  ____.<br>';

code += '   /  _____/|    |   |   \\__    ___|_   ___ \\ /   |   \\   /  _____/|   \\_   _____/ \\   \\ /   / |    |<br>';
code += '  /   \\  ___|    |   |   | |    |  /    \\  \\//    ~    \\ /   \\  ___|   ||    __)    \\   Y   /  |    |<br>';
code += '  \\    \\_\\  \\    |___|   | |    |  \\     \\___\\    Y    / \\    \\_\\  \\   ||     \\      \\     /\\__|    |<br>';
code += '   \\________/________\\___| |____|   \\________/\\___|___/   \\________/___|\\_____/       \\___/\\________|<br>';
code += '</pre></div>';

code += '<div id="morestuff">';
code += '<div id="aboutbox">GLITCH GIF VJ is a 100% HTML5/JAVASCRIPT VJ software that run into your WEB Browser. <br> Use chrome for better perf and midi control<br>If you like this software and use it please share it. Hit me if you have ideas to make it better.<br>I\'m also open to collab and for hire so don\'t hesitate to <a href="https://azopcorp.com/contact">contact me.</a>   <br> Made With love by AZOPCORP. 2016. <br>THIS SOFTWARE IS PROVIDED "AS IS" AND COMES WITH ABSOLUTLY NO WARRANTIES!</div>';
code += '<input type="text" id="midiarrayinput" placeholder="external midi map"><br><br><div id="link" ><a href="https://azopcorp.com/serve/html/ggvmanual">USER MANUAL</a><br><a href="https://www.youtube.com/watch?v=Cumk8Jp6BNQ">VIDEO TUTORIAL</a><br><a href="https://github.com/AZOPCORP/GLITCHGIFVJ">SOURCE CODE</a></div> </div>';

$('body').append(code);
